<?php


	class Coupon_Campaigns_Custom_Post_Types {

       public function __construct() {
        $this->init();
        $this->add_manage_edit_columns();

       }













 

   function register_plugin_post_types() {

  

// Set UI labels for Custom Post Type

     $labels = array(

        'name'                => _x( 'Campaigns', 'Post Type General Name', 'twentythirteen' ),

        'singular_name'       => _x( 'Campaign', 'Post Type Singular Name', 'twentythirteen' ),

        'menu_name'           => __( 'Campaigns', 'twentythirteen' ),

        'parent_item_colon'   => __( 'Parent Movie', 'twentythirteen' ),

        'all_items'           => __( 'All Campaigns', 'twentythirteen' ),

        'add_new_item'        => __( 'Add New Campaign', 'twentythirteen' ),

        'add_new'             => __( 'Add New', 'twentythirteen' ),

        'search_items'        => __( 'Search Campaign', 'twentythirteen' ),

        'not_found'           => __( 'Not Found', 'twentythirteen' ),

        'not_found_in_trash'  => __( 'Not found in Trash', 'twentythirteen' ),

    );

     

// Set other options for Custom Post Type

     

    $args = array(

        'label'               => __( 'campaigns', 'twentythirteen' ),

        'description'         => __( 'Campaign', 'twentythirteen' ),

        'labels'              => $labels,

        // Features this CPT supports in Post Editor

        'supports'            => array( 'title', 'editor', 'excerpt', 'author','custom-fields', ),

        // You can associate this CPT with a taxonomy or custom taxonomy. 

        'taxonomies'          => array( 'genres' ),

        /* A hierarchical CPT is like Pages and can have

        * Parent and child items. A non-hierarchical CPT

        * is like Posts.

        */ 

        'hierarchical'        => false,

        'public'              => true,

        'show_ui'             => true,

        'show_in_menu'        => true,

        'show_in_nav_menus'   => true,

        'show_in_admin_bar'   => true,

        'menu_position'       => 5,

        'can_export'          => true,

        'has_archive'         => true,

        'exclude_from_search' => false,

        'publicly_queryable'  => true,

        'capability_type'     => 'page',

    );

     

    // Registering your Custom Post Type

    register_post_type( 'campaign', $args );

 

}

 

/* Hook into the 'init' action so that the function

* Containing our post type registration is not 

* unnecessarily executed. 

*/

 

add_action( 'init', 'register_plugin_post_types', 0 );



















































}

