<?php
        include("is_login.php");
        $transid=$_GET['id'];
        session_start();
        //echo "<pre>";
        //echo $transid;
        //print_r($_SESSION);
        $firstname=$_SESSION['firstname'];
        $lastname=$_SESSION['lastname'];
        $date1=$_SESSION['date1'];
        $touroperator=$_SESSION['touroperator'];
        $address=$_SESSION['address'];
        $price=$_SESSION['price'];
        $tax=$_SESSION['tax'];
        $subtotal=$_SESSION['subtotal'];
        $nationality=$_SESSION['nationality'];
        $countryesta=$_SESSION['countryesta'];
        $email=$_SESSION['email'];
        $cctype=$_SESSION['cctype'];
        $ccnum=$_SESSION['ccnum'];
        $emonth=$_SESSION['emonth'];
        $eyear=$_SESSION['eyear'];
        $csc=$_SESSION['csc'];
        $path=$_SESSION['path'];
        $ispath=$_SESSION['ispath'];
        $redirecturl=$_SESSION['redirecturl'];
        $order_id=$_SESSION['order_id'];
        $total_price=$_SESSION['total_price'];
        $conID=$_SESSION['conID'];
	       
        $currentDate = date("d-m-Y");
        $pDate = $app->infuDate($currentDate);
        //$result = $app->chargeInvoice($order_id,"Orderform Payment",$creditCardID,13,false);
        $result = $app->manualPmt($order_id, (float)$total_price,$pDate,'','',false);
        $order_id=$order_id;
        $orders_data = array('_Paid'  => 'YES','_WorldpayTransactionID' =>$transid);
        $orderfinalID = $app->dsUpdate("Job", $order_id, $orders_data);
        $contactId =$conID;
        $tagId = 7012;
        $tagId1 = 7014;
        $result1 = $app->grpAssign($contactId, $tagId);
        $result1 = $app->grpRemove($contactId, $tagId1);
          //echo json_encode($result);
          //echo "<pre>";
          header('Location:'.$redirecturl);
          exit();